[package]
name = "monorail"
version = "1.0.0"
authors = ["Patrick Nordahl <plnordahl@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
trie-rs = "0.1"
git2 = { version = "0.13", default-features = false }
