[package]
name = "monorail"
description = "A monorepo overlay for version control systems."
license = "MIT"
homepage = "https://github.com/pnordahl/monorail"
repository = "https://github.com/pnordahl/monorail"
version = "1.0.1"
authors = ["Patrick Nordahl <plnordahl@gmail.com>"]
edition = "2021"
keywords = ["monorail", "monorepo"]

[dependencies]
clap = "2"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
trie-rs = "0.1"
git2 = { version = "0.13", default-features = false }
