[package]
name = "monorail"
description = "A monorepo overlay."
license = "MIT"
homepage = "https://github.com/pnordahl/monorail"
repository = "https://github.com/pnordahl/monorail"
version = "2.1.0"
authors = ["Patrick Nordahl <plnordahl@gmail.com>"]
edition = "2021"
keywords = ["monorail", "monorepo"]

[dependencies]
clap = "4.5"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
trie-rs = "0.4"
git2 = { version = "0.19", default-features = false }
