# See https://github.com/toml-lang/toml#spec for details on how TOML is structured.

# Directory to place logs, caches, and other runtime outputs.
# Optional. Default: "monorail-out"
output_dir = "monorail-out"

[vcs]
# The version control system that the repository uses.
# Required. One of: ["git"]
use = "git"

# An array of targets to configure.
[[targets]]
# The path for this target. The value is relative to the repository root. Targets with 
# duplicate paths will return an error.
# Change paths that lie in this directory structure will add this target
# to the output target list.
# * Required
path = "target1"

# Path prefixes to ignore when determining if a change should affect this target.
# These are evaluated last, and will override a matching 'link' or 'uses'.
# Change paths that lie in subdirectories will remove this target from the output list.
# * Optional. Default: []
ignores = [
    "target1/ignore1"
]
# References to path prefixes outside of this target's path that 
# should affect this target. If a provided path A lies within 
# another target B's path, then this will establish a dependency
# between this target A on B. Change paths that lie in this 
# directory structure will add this target to the output target 
# list, and optionally the target grouping.
# * Optional. Default: []
uses = [
    "common/library1"
]

# Path relative to target.path of a file to use when executing
# functions with `monorail run`. This can be a file of any 
# supported file type.
# * Optional. Default: "monorail.sh"
run = "monorail.sh"