# See https://github.com/toml-lang/toml#spec for details on how TOML is structured.

[vcs]
# The version control system that the repository uses.
# Required. One of: ["git"]
use = "git"

[vcs.git]
# The branch used for trunk-based development and tagged releases.
# * Optional. Default: "master"
trunk = "master"

# The remote to push release tags to.
# * Optional. Default: "origin"
remote = "origin"

# A prefix for the tag refspec to use when pushing release tags.
# * Optional. Default: "refs/tags"
tags_refspec_prefix = "refs/tags"

[extension]
# The extension to use for running commands.
# * Required. One of: ["bash"]
use = "bash"

# Configuration for the bash extension 'exec' subcommand. 
[extension.bash.exec]
# The path to the entrypoint script for any group or target. The value is relative to each group and target.
# * Optional. Default: "support/script/monorail-exec.sh"
entrypoint = "support/script/monorail-exec.sh"

# A list of scripts to source (in order) prior to execution of an entrypoint script. The values are relative to the repository root.
# * Optional. Default: []
source = []

# An array of targets to configure.
[[targets]]
# The path for this target. The value is relative to the repository root. Targets with 
# duplicate paths will return an error.
# Change paths that lie in this directory structure will add this target
# to the output target list.
# * Required
path = "target1"

# Path for which matching changes should affect all targets that are subdirectories of this target. 
# Change paths that lie in this directory structure will add this target
# and all targets that lie in subdirectories to the output target list.
# * Optional. Default: []
links = [
    "target1/vendor",
]

# Path prefixes to ignore when determining if a change should affect this target.
# These are evaluated last, and will override a matching 'link' or 'uses'.
# Change paths that lie in subdirectories will remove this target from the output list.
# * Optional. Default: []
ignores = [
    "target1/ignore1"
]
# References to path prefixes outside of this target's path that should affect 
# this target.
# Change paths that lie in this directory structure will add this target
# to the output target list.
# * Optional. Default: []
uses = [
    "common/library1"
]
