name: monorail

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  monorail:
    name: monorail
    runs-on: ubuntu-latest
    env:
      MONORAIL_TEST_DIR : ${{ github.workspace }}/tmp
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - run: |
          sudo chown -R $USER:$USER ${{ github.workspace }}
          mkdir -p "$MONORAIL_TEST_DIR"
          git config --global user.name "a b"
          git config --global user.email "a@b.com"
      - run: cargo clippy --locked -- -D warnings
      - run: cargo build --locked
      - run: cargo test --locked -- --nocapture
  monorail-windows:
    name: monorail-windows
    runs-on: windows-latest
    env:
      MONORAIL_TEST_DIR : ${{ github.workspace }}/tmp
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - run: |
          mkdir "%MONORAIL_TEST_DIR%"
          dir "%MONORAIL_TEST_DIR%"
          git config --global user.name "a b"
          git config --global user.email "a@b.com"
      - run: cargo clippy --locked -- -D warnings
      - run: cargo build --locked
      - run: cargo test --locked -- --nocapture
